# Generated by Django 3.1.4 on 2020-12-21 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweeted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
