# Generated by Django 3.1.4 on 2020-12-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20201221_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='displayName',
            field=models.CharField(default='displayName', max_length=50),
        ),
        migrations.AddField(
            model_name='tweet',
            name='profile_pic',
            field=models.ImageField(default='pic', upload_to=''),
        ),
        migrations.AddField(
            model_name='tweet',
            name='username',
            field=models.CharField(default='username', max_length=50),
        ),
    ]
