# Generated by Django 3.1.4 on 2020-12-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20201222_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='profile_pic',
            field=models.URLField(default='pic'),
        ),
    ]
