# Generated by Django 3.1.4 on 2020-12-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20201226_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='author',
            new_name='owner',
        ),
    ]
